// swift-tools-version:5.9
import PackageDescription

// This package exposes the library targets (HyperXProtocol, HyperXCore) and
// CLI tools (ValidateProtocol, HIDProbe). The SwiftUI app (`HyperXRGB`) lives
// in `App/HyperXRGB/` and is built via the Xcode project (generated by
// xcodegen from `project.yml`), which consumes this package as a local
// dependency.
let package = Package(
    name: "HyperXRGB",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "HyperXProtocol", targets: ["HyperXProtocol"]),
        .library(name: "HyperXCore", targets: ["HyperXCore"]),
    ],
    targets: [
        .target(name: "HyperXProtocol"),
        .target(
            name: "HyperXCore",
            dependencies: ["HyperXProtocol"]
        ),
        .executableTarget(
            name: "ValidateProtocol",
            dependencies: ["HyperXProtocol"]
        ),
        .executableTarget(
            name: "HIDProbe",
            dependencies: ["HyperXCore", "HyperXProtocol"]
        ),
        .testTarget(
            name: "HyperXProtocolTests",
            dependencies: ["HyperXProtocol"]
        ),
    ]
)
